package com.guzloo.excalseet;

import jakarta.servlet.http.HttpServletResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.util.List;

@Component
@Slf4j
public class ExportAllStudentsToExcelScheduler {

    @Autowired
    private StudentsRepo studentsRepo;

    @Autowired
    private ExcelService excelService;
   // @Scheduled(cron = "0 0 1 * * ?") // Daily at 1 AM
   @Scheduled(cron = "*/30 * * * * *")
    public void exportAllStudentsToExcel() throws IOException {
        List<Student> students = studentsRepo.findAll();
        excelService.generateExcelToDisk(students);
        System.out.println("Student list generated by batch job");
    }


}
